Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/cafonsop-cfn-artifacts/92ed32e223ed4c1633dcad52eb7dfdde.template
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the ALB
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      VpcId:
        Fn::GetAtt:
        - NetworkStack
        - Outputs.VpcId
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
      - Ref: ALBSecurityGroup
      Subnets:
      - Fn::GetAtt:
        - NetworkStack
        - Outputs.PublicSubnetAId
      - Fn::GetAtt:
        - NetworkStack
        - Outputs.PublicSubnetBId
      Type: application
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: 5
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::GetAtt:
        - NetworkStack
        - Outputs.VpcId
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: ALBTargetGroup
      LoadBalancerArn:
        Ref: ALB
      Port: 80
      Protocol: HTTP
Outputs:
  AppUrl:
    Description: The URL to the Application Load Balancer fronting the cluster.
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - ALB
          - DNSName
